server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root

## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
        # health,info..
  security:
    enabled: false