server:
  port: 9000
spring:
  application:
    name: res-service #指定服务名
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://127.0.0.1:3306/cloud-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
      servlet:
        multipart:
          max-file-size: 512000     # 文件上传大小限制为500kb
          max-request-size: 512000  # 请求大小限制为500kb
      session:  # springSession设置
        store-type: redis
  jpa:
    database: MySQL
    show-sql: true

## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
    web: # 暴露触发消息总线的地址
      exposure:
        include: bus-refresh
  endpoints:
    web:
      exposure:
        include: '*'
        # health,info..
  security:
    enabled: false
    
## 自定义配置，用于验证bus总线和@RefreshScope注解是否失效
sms:
  ip: 0.0.0.0
